### ISSUE TITLE
How to solve GoError: failed to upgrade database: sqlite3: disk I/O error 

### ISSUE THREAD

**Issue by frmdeveloper** [ncruces/go-sqlite3#109]
When I run with wasm nodejs, I get an error like this 
![Screenshot_20240628_195725_Termux](https://github.com/ncruces/go-sqlite3/assets/80396521/093fe837-461d-40f6-81d7-3ce7cdfe01fe)

```go
import (
  ...
      "go.mau.fi/whatsmeow/store/sqlstore"
    _ "github.com/ncruces/go-sqlite3/driver"
    _ "github.com/ncruces/go-sqlite3/embed"
)

...
container, err := sqlstore.New("sqlite3", "file:tes.db", dbLog)
```

**Comment by ncruces** [comment]
I have… no idea?

What's _"wasm nodejs"_? What's `sqlstore`? Never heard of it. `_foreign_keys=on` does nothing for this driver.

How can I reproduce the bug? I copy those 6 lines to a file and run it?

Your chances of getting help will improve incredibly if you post a good bug report.

**Comment by frmdeveloper** [comment]
> What's _"wasm nodejs"_?

i am trying to run WebAssembly using NodeJS 
```
$ env GOOS=js GOARCH=wasm go build -o test.wasm
$ node $(go env GOROOT)/misc/wasm/wasm_exec_node.js test.wasm
```
---
> What's sqlstore? Never heard of it. _foreign_keys=on does nothing for this driver.

just forget about that

**Comment by ncruces** [comment]
OK you're nesting Wasm inside Wasm. That's [not really the intended use](https://github.com/ncruces/go-sqlite3/discussions/15) for this.

Still, the issue is probably that file locking is not supported with either `wasm`/`js` or `wasm`/`wasip1`.

See [this](https://github.com/ncruces/go-sqlite3/tree/main/vfs#file-locking), and use [`nolock=1`](https://sqlite.org/uri.html#urinolock).
