### ISSUE TITLE
How do I use the backup API from Gorm?

### ISSUE THREAD

**Issue by Xe** [ncruces/go-sqlite3#141]
I'm trying to use the online backup api with this bit of code:
```go
func (d *DAO) backup(ctx context.Context, to string) error {
	db, err := d.db.DB()
	if err != nil {
		return fmt.Errorf("failed to get database connection: %w", err)
	}

	if err := db.Ping(); err != nil {
		return fmt.Errorf("failed to ping database: %w", err)
	}

	conn, err := db.Conn(ctx)
	if err != nil {
		return fmt.Errorf("failed to get database connection: %w", err)
	}

	defer conn.Close()

	if err := conn.Raw(func(dca any) error {
		conn, ok := dca.(*sqlite3.Conn)
		if !ok {
			return fmt.Errorf("db connection is not a sqlite3 connection, it is %T", dca)
		}

		bu, err := conn.BackupInit("main", to)
		if err != nil {
			return fmt.Errorf("failed to initialize backup: %w", err)
		}
		defer bu.Close()

		var done bool
		for !done {
			done, err = bu.Step(bu.Remaining())
			if err != nil {
				return fmt.Errorf("failed to backup database: %w", err)
			}
		}

		if err := bu.Close(); err != nil {
			return fmt.Errorf("failed to close backup: %w", err)
		}

		return nil
	}); err != nil {
		return fmt.Errorf("failed to backup database: %w", err)
	}

	return nil
}
```

When I run it, I get this error:

```
failed to backup database: db connection is not a sqlite3 connection, it is *driver.conn
```

I can't type assert to a private type, how do I use the backup API?

**Comment by ncruces** [comment]
Yeah, this is probably not the best API design, certainly not very discoverable.

You can assert [`sqlite3.DriverConn`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#DriverConn). Then call `Raw()` on it to get the `*sqlite3.Conn`.

I initially didn't want the `driver` package to expose *any* API (it was meant to be a blank import); then I did add some APIs; then someone wanted the driver exposed; then I've gone back and forth on that. At this point, some stuff that's really only useful to `database/sql` is in package `sqlite3` rather than `driver`, because _"reasons."_

I'm still not sure what the separation should be like. I don't want people to depend on `database/sql` (or register a driver) if they don't want to. I also don't want to duplicate everything in both places. Same thing with separating the `vfs` package, turns out to be painful because of circular deps.

**Comment by ncruces** [comment]
For reference, the list of APIs that are meant to be used with the driver (but which manage not to depend on `database/sql`, so they're in package `sqlite3`):
- [`sqlite3.DriverConn`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#DriverConn) to type assert the connection
- [`sqlite3.JSON(value)`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#JSON) to bind/scan JSON
- [`sqlite3.Pointer[T](value)`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#Pointer) to bind a pointer
- [`sqlite3.ZeroBlob(size)`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#ZeroBlob) to bind a zero blob
- [`sqlite3.TimeFormat.Scanner(ptr)`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#TimeFormat.Scanner) to scan a `time.Time` in a specific format
- [`sqlite3.TimeFormat.Encode(value)`](https://pkg.go.dev/github.com/ncruces/go-sqlite3#TimeFormat.Encode) to bind a `time.Time` in a specific format

**Comment by Xe** [comment]
> You can assert [sqlite3.DriverConn](https://pkg.go.dev/github.com/ncruces/go-sqlite3#DriverConn), then call Raw() on it to get the *sqlite3.Conn.

This worked. Thanks!

**Comment by ncruces** [comment]
If you have any input on improvements, it'd be very appreciated.
Otherwise I'll try to think of something.
